server:
  port: 9999
spring:
  datasource:
    name: iot_sys
    url: jdbc:mysql://192.168.10.243:3306/iot_sys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yzm-iot
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    hostname: iot-uid
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/