server:
  port: 8211
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: iot_sys
    url: jdbc:mysql://192.168.10.243:3306/iot_sys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yzm-iot
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select '1'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    host: 192.168.10.244
    port: 5672
    username: yzm-iot
    password: 123456
  zipkin:
    base-url: http://localhost:9411

mybatis:
  basepackage: com.yzm.iot.sys.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

swagger:
  enabled: true
  base-package: com.yzm.iot.sys
  title: iot-sys
  version: 1.0.0.SNAPSHOT
  description: 系统管理功能
  contact:
    name: admin

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"  # 由于SpringBoot限制，大多数端点不会通过HTTP开放，所以这里选择全部